<?php
/* @var $this ThreeAArt_Theme_Block_Home */
?>
<h1>Herzlich Willkommen im Künstler Bereich von 3aArt</h1>
<p>Bitte erstellen Sie sich einen Account, in dem Sie hier klicken:<p>

<p>
    <a href="<?php echo $this->getUrl('customer/account/login'); ?>">&lt;&lt; Zur Registrierung / zum Log-In Bereich</a>
</p>

<address>Judith Grote<br />
    Art Basel Gallery UG<br />
    Erika-Köth Strasse 5<br />
    85598 Baldham<br /> <br />
    Ust-Id-Nr.: DE277782863<br />
    HRB: 191197
</address>